name: Build and Deploy Docker Image to Azure octopus
on:
  push:
    branches:
      - main
env:
  Azure_Container_Registry: azurepoc123
  Container_App_Name: ca_name
  Resource_Group: cfsh-cc-d-rg02
jobs:
  build-and-push:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          registry: ${{ env.Azure_Container_Registry }}.azurecr.io
          username: ${{ secrets.user_name }}
          password: ${{ secrets.password }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}



  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to Web App
        run: |
          ACR_LOGIN_SERVER=${{ secrets.ACR_NAME }}.azurecr.io
          IMAGE_NAME=$ACR_LOGIN_SERVER/myapp:latest

          az webapp config container set \
            --name ${{ secrets.WEBAPP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --docker-custom-image-name $IMAGE_NAME \
            --docker-registry-server-url https://$ACR_LOGIN_SERVER
            
