name: Build and Deploy Docker Image to Azure octopus
on:
  push:
    branches:
      - main
env:
  AZURE_CONTAINER_REGISTRY: azurepoc123
  Resource_Group: cfsh-cc-d-rg02
  CONTAINER_APP_NAME: azurepoc1234
permissions:
      id-token: write
      contents: read
jobs: 
  az-login-test:
    runs-on: ubuntu-latest
    steps:
      - name : Check Az version before installing
        run: az --version
        
      - name: Installing Az CLI Edge build 
        run: |
           cd ../..
           CWD="$(pwd)"
           python3 -m venv canary-venv
           . canary-venv/bin/activate
           echo "***********activated virual environment**********" 
           python3 -m pip install --upgrade pip
           echo "***************started installing cli edge build******************"
           pip3 install -q --upgrade --pre azure-cli --extra-index-url https://azurecliprod.blob.core.windows.net/edge --no-cache-dir --upgrade-strategy=eager
           echo "***************installed cli Edge build*******************"    
           echo "$CWD/canary-venv/bin" >> $GITHUB_PATH
           az --version
        
      - name: Login to Azure
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: PUSH TO ACR
        uses: docker/build-push-action@v6
        with:
           push: true
           tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
           file: Dockerfile
      - name: 'Az CLI login with subscription OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENTID }}
          secret-id: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANTID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTIONID }} 
     # - name: Azure Login Web App
      #  uses: azure/login@v2
      #  with:
        #   creds: ${{ secrets.AZURE_CREDENTIALS }}
       #   allow-no-subscriptions: true

      - name: Deploy to webapp
        uses: azure/container-apps-deploy-action@v1
        with: 
           imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
           resourceGroup: ${{ env.Resource_Group }}
           containerAppName: ${{ env.CONTAINER_APP_NAME }}
           
 
