# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - azurepoc123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://azurepoc123.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0cb98d702e6e414ca53b103ef32b826c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_42a7fa0a0f0d4755884a2649d0ef5af7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: azurepoc123.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cb98d702e6e414ca53b103ef32b826c }}/azurepoc123:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azurepoc123'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2724331295ee40909d238719cc89575c }}
        images: 'azurepoc123.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0cb98d702e6e414ca53b103ef32b826c }}/azurepoc123:${{ github.sha }}'